/*
 * This source file was generated by the Gradle 'init' task
 */
package uve;

import java.sql.Date;
import java.time.LocalDate;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import uve.Model.Vehiculo;
import uve.Model.Coche.Automovil;
import uve.Model.Coche.Camioneta;
import uve.Model.Service.Reparacion;

public class App {
    
    public static void main(String[] args) {

        try {

            Vehiculo car = new Camioneta("Toyota", "4325", "ABC1234");
            Vehiculo car2 = new Automovil ("Honda", "Civic", "XYZ5678");
            //Encender camioneta
            car.encender();

            car2.encender();

            //reparacion de la camioneta
          


            
            Reparacion reparacion = new Reparacion("cambio de aceite", 100, "10/02/2020", "aceite");
            Reparacion reparacion2 = new Reparacion("cambio de llanta", 300, "05/10/2006", "llanta");
            //Descripcion de la reparacion
            System.out.println("Descripcion de la reparacion 1: " + reparacion.getDescripcion());
            System.out.println("Descripcion de la reparacion 2: " + reparacion2.getDescripcion());

            
            car.agregarReparacionHistoria(reparacion);
            car2.agregarReparacionHistoria(reparacion2);
            //ver reparacion de la camioneta
            System.out.println(car.getReparacion());
            System.out.println(car2.getReparacion());
            System.out.println(car.getHistoricoReparaciones());
            System.out.println(car2.getHistoricoReparaciones());

            car.ReparacionesAHistorico();
            car2.ReparacionesAHistorico();
            
            System.out.println(car.getHistoricoReparaciones());
            System.out.println(car2.getHistoricoReparaciones());

        } catch (Exception e) {
            System.out.println("Hubo un error : " + e.getMessage());
        }


    }


}
